FROM openjdk:17-bullseye

RUN apt-get update
RUN apt-get install wait-for-it
# copy only the artifacts we need from the first stage and discard the rest
COPY ./target/flightmonitor-0.0.1-SNAPSHOT.jar ./flightmonitor.jar

COPY src/docker/start.sh start.sh
RUN chmod +x start.sh
# set the startup command to execute the jar
ENTRYPOINT ["./start.sh"]

